/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/announcements/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["announcements_active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/phase/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["phase_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["screen_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens/{slug}/bundle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["screen_bundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActiveAnnouncementRow: {
            id: string;
            level: components["schemas"]["LevelEnum"];
            takeover: boolean;
            text: components["schemas"]["Bilingual"];
            /** Format: date-time */
            ends_at: string | null;
            screens: string[];
        };
        ActiveAnnouncements: {
            results: components["schemas"]["ActiveAnnouncementRow"][];
        };
        Announcement: {
            id: string;
            level: components["schemas"]["LevelEnum"];
            takeover: boolean;
            text: components["schemas"]["Bilingual"];
            /** Format: date-time */
            ends_at: string | null;
        };
        Bilingual: {
            hu: string;
            en: string;
        };
        Bundle: {
            version: string;
            /** Format: date-time */
            generated_at: string;
            screen: components["schemas"]["Screen"];
            phase: components["schemas"]["Phase"] | null;
            clock: components["schemas"]["Clock"];
            event: components["schemas"]["EventSummary"];
            announcement: components["schemas"]["Announcement"] | null;
            passes: components["schemas"]["Pass"][];
            warnings: string[];
            preview: boolean;
            default_screen: string;
        };
        Clock: {
            /** Format: date-time */
            now: string;
            timezone: string;
        };
        EventSummary: {
            name: string;
            tagline: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
        };
        GameRef: {
            slug: string;
            name: string;
            short: string;
            color_bg: string;
            color_text: string;
        };
        /**
         * @description * `hu` - hu
         *     * `en` - en
         *     * `both` - both
         * @enum {string}
         */
        LangEnum: "hu" | "en" | "both";
        /**
         * @description * `slide` - slide
         *     * `hu` - hu
         *     * `en` - en
         * @enum {string}
         */
        LanguageModeEnum: "slide" | "hu" | "en";
        /**
         * @description * `info` - info
         *     * `warning` - warning
         *     * `urgent` - urgent
         * @enum {string}
         */
        LevelEnum: "info" | "warning" | "urgent";
        /**
         * @description * `manual` - manual
         *     * `auto` - auto
         * @enum {string}
         */
        ModeEnum: "manual" | "auto";
        Pass: {
            key: string;
            slide: string;
            layout: string;
            source: string;
            lang: components["schemas"]["LangEnum"];
            duration_ms: number;
            content: components["schemas"]["SlideContent"];
            live: unknown | null;
        };
        Phase: {
            key: string;
            name: components["schemas"]["Bilingual"];
            mode?: components["schemas"]["ModeEnum"];
        };
        ScheduleEntryView: {
            time: string;
            type: components["schemas"]["TypeEnum"];
            label: string;
            title: components["schemas"]["Bilingual"];
            note: components["schemas"]["Bilingual"];
            game: components["schemas"]["GameRef"] | null;
            /** Format: date-time */
            starts_at: string;
        };
        ScheduleView: {
            now: components["schemas"]["ScheduleEntryView"][];
            next: components["schemas"]["ScheduleEntryView"][];
            later: components["schemas"]["ScheduleEntryView"][];
            upcoming: components["schemas"]["ScheduleEntryView"][];
        };
        Screen: {
            slug: string;
            name: string;
            refresh_seconds: number;
            show_clock: boolean;
            show_progress: boolean;
            language_mode: components["schemas"]["LanguageModeEnum"];
        };
        SlideColumn: {
            title: components["schemas"]["Bilingual"];
            items: components["schemas"]["SlideItem"][];
        };
        SlideContent: {
            kicker?: components["schemas"]["Bilingual"];
            title: components["schemas"]["Bilingual"];
            body?: components["schemas"]["Bilingual"];
            footer?: components["schemas"]["Bilingual"];
            empty?: components["schemas"]["Bilingual"];
            items: components["schemas"]["SlideItem"][];
            columns: components["schemas"]["SlideColumn"][];
            labels: {
                [key: string]: components["schemas"]["Bilingual"];
            };
            link?: components["schemas"]["SlideLink"] | null;
        };
        SlideItem: {
            hu: string;
            en: string;
            icon?: string;
        };
        SlideLink: {
            url: string;
            label: components["schemas"]["Bilingual"];
            qr_payload: string;
        };
        /**
         * @description * `play` - play
         *     * `break` - break
         *     * `highlight` - highlight
         * @enum {string}
         */
        TypeEnum: "play" | "break" | "highlight";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    announcements_active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAnnouncements"];
                };
            };
        };
    };
    phase_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Phase"];
                };
            };
        };
    };
    schedule_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleView"];
                };
            };
        };
    };
    screen_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Screen"][];
                };
            };
        };
    };
    screen_bundle: {
        parameters: {
            query?: {
                /** @description hu, en or both (preview only). */
                lang?: string;
                /** @description Phase key override (staff only). */
                phase?: string;
                /** @description Slide key to render alone. */
                preview?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bundle"];
                };
            };
        };
    };
}
