# Generated by Django 6.1.2 on 2026-10-06 13:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import signage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("urgent", "Urgent"),
                        ],
                        default="info",
                        max_length=7,
                    ),
                ),
                ("takeover", models.BooleanField(default=False)),
                ("text_hu", models.CharField(max_length=300)),
                ("text_en", models.CharField(max_length=300)),
            ],
            options={
                "ordering": ("key",),
            },
            bases=(models.Model, signage.models.Bilingual),
        ),
        migrations.CreateModel(
            name="DisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background",
                    models.FileField(
                        blank=True,
                        help_text="1920x1080 SVG. Leave empty to use the bundled artwork.",
                        upload_to="background/",
                        validators=[signage.models._validate_svg],
                    ),
                ),
                ("default_screen_slug", models.SlugField(default="main")),
                ("stage_width", models.PositiveSmallIntegerField(default=1920)),
                ("stage_height", models.PositiveSmallIntegerField(default=1080)),
                ("safe_x", models.PositiveSmallIntegerField(default=96)),
                ("safe_y", models.PositiveSmallIntegerField(default=204)),
                ("safe_width", models.PositiveSmallIntegerField(default=1728)),
                ("safe_height", models.PositiveSmallIntegerField(default=564)),
            ],
            options={
                "verbose_name": "Display settings",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("short", models.CharField(max_length=40)),
                ("hosted", models.BooleanField(default=False)),
                ("tournament", models.BooleanField(default=False)),
                (
                    "projectile_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Game keys the Projectile server list uses.",
                    ),
                ),
                (
                    "color_bg",
                    models.CharField(
                        default="#777777",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Use a six digit hex colour like #aa0000.",
                            )
                        ],
                    ),
                ),
                (
                    "color_text",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Use a six digit hex colour like #aa0000.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("projectile", "Projectile game server list"),
                            ("bracket", "Bracket tournament system"),
                            ("streams", "Streams directory"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="API root without a trailing slash, for example https://servers.ctrl-alt-gg.hu/api",
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "No authentication"),
                            ("basic", "HTTP Basic (username and password)"),
                            ("bearer", "Bearer token"),
                            ("header", "Custom header"),
                        ],
                        default="none",
                        max_length=6,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=120)),
                ("password", models.CharField(blank=True, max_length=240)),
                ("token", models.CharField(blank=True, max_length=500)),
                (
                    "header_name",
                    models.CharField(blank=True, default="Authorization", max_length=60),
                ),
                ("verify_tls", models.BooleanField(default=True)),
                (
                    "ca_bundle",
                    models.CharField(
                        blank=True,
                        help_text="Path to a CA bundle for a venue certificate.",
                        max_length=300,
                    ),
                ),
                ("connect_timeout", models.FloatField(default=2.0)),
                ("read_timeout", models.FloatField(default=4.0)),
                (
                    "cache_seconds",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "tournament_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Bracket only. Empty picks the first open tournament.",
                        null=True,
                    ),
                ),
                (
                    "mirror_announcement",
                    models.BooleanField(
                        default=False,
                        help_text="Projectile only. Show its announcement as an info bar.",
                    ),
                ),
            ],
            options={
                "ordering": ("kind",),
            },
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("name_hu", models.CharField(max_length=60)),
                ("name_en", models.CharField(max_length=60)),
                (
                    "starts",
                    models.TimeField(help_text="Local wall-clock time when this phase begins."),
                ),
                (
                    "day_offset",
                    models.SmallIntegerField(
                        default=0,
                        help_text="0 on the event's first day, 1 after midnight.",
                    ),
                ),
                ("order", models.SmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("order", "day_offset", "starts"),
            },
            bases=(models.Model, signage.models.Bilingual),
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "refresh_seconds",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "language_mode",
                    models.CharField(
                        choices=[
                            ("slide", "Follow each slide"),
                            ("hu", "Magyar"),
                            ("en", "English"),
                        ],
                        default="slide",
                        max_length=5,
                    ),
                ),
                ("show_clock", models.BooleanField(default=True)),
                ("show_progress", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Ctrl-Alt-GG", max_length=100)),
                (
                    "tagline",
                    models.CharField(blank=True, default="GL&HF, IRL.", max_length=100),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "timezone",
                    models.CharField(default="Europe/Budapest", max_length=60),
                ),
                ("venue_name", models.CharField(blank=True, max_length=120)),
                ("venue_address", models.CharField(blank=True, max_length=200)),
                (
                    "venue_lat",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "venue_lng",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                ("entrance_note_hu", models.TextField(blank=True)),
                ("entrance_note_en", models.TextField(blank=True)),
                ("parking_hu", models.TextField(blank=True)),
                ("parking_en", models.TextField(blank=True)),
                ("assembly_point_hu", models.CharField(blank=True, max_length=200)),
                ("assembly_point_en", models.CharField(blank=True, max_length=200)),
                ("wifi_ssid", models.CharField(blank=True, max_length=64)),
                ("wifi_password", models.CharField(blank=True, max_length=128)),
                (
                    "wifi_security",
                    models.CharField(
                        choices=[
                            ("WPA", "WPA/WPA2/WPA3"),
                            ("WEP", "WEP"),
                            ("nopass", "Open"),
                        ],
                        default="WPA",
                        max_length=6,
                    ),
                ),
                ("wifi_note_hu", models.CharField(blank=True, max_length=200)),
                ("wifi_note_en", models.CharField(blank=True, max_length=200)),
                (
                    "links",
                    models.JSONField(blank=True, default=dict, help_text="Mapping of key to URL."),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "organizers",
                    models.JSONField(blank=True, default=list, help_text="List of names."),
                ),
                (
                    "phase_mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "From the clock")],
                        default="manual",
                        max_length=6,
                    ),
                ),
                (
                    "current_phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="signage.phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
            },
            bases=(models.Model, signage.models.Bilingual),
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time", models.TimeField()),
                ("day_offset", models.SmallIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("play", "Play"),
                            ("break", "Break"),
                            ("highlight", "Highlight"),
                        ],
                        default="play",
                        max_length=9,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=60)),
                ("title_hu", models.CharField(max_length=120)),
                ("title_en", models.CharField(max_length=120)),
                ("note_hu", models.CharField(blank=True, max_length=200)),
                ("note_en", models.CharField(blank=True, max_length=200)),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signage.game",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schedule entries",
                "ordering": ("day_offset", "time", "order"),
            },
            bases=(models.Model, signage.models.Bilingual),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text_hu", models.CharField(max_length=300)),
                ("text_en", models.CharField(max_length=300)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("urgent", "Urgent"),
                        ],
                        default="info",
                        max_length=7,
                    ),
                ),
                (
                    "takeover",
                    models.BooleanField(
                        default=False,
                        help_text="Replace the rotation while active instead of showing a bar.",
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, help_text="Empty means until ended.", null=True
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signage.announcementtemplate",
                    ),
                ),
                (
                    "screens",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Empty means every screen.",
                        related_name="announcements",
                        to="signage.screen",
                    ),
                ),
            ],
            options={
                "ordering": ("-starts_at",),
            },
            bases=(models.Model, signage.models.Bilingual),
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(max_length=60, primary_key=True, serialize=False),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("hero", "hero"),
                            ("list", "list"),
                            ("split", "split"),
                            ("qr", "qr"),
                            ("credentials", "credentials"),
                            ("now_next", "now_next"),
                            ("schedule", "schedule"),
                            ("servers", "servers"),
                            ("tournament", "tournament"),
                            ("streams", "streams"),
                            ("countdown", "countdown"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("static", "Static text"),
                            ("live:schedule", "Live: schedule"),
                            ("live:clock", "Live: clock"),
                            ("live:projectile", "Live: Projectile servers"),
                            ("live:bracket", "Live: Bracket tournament"),
                            ("live:streams", "Live: Streams"),
                        ],
                        default="static",
                        max_length=16,
                    ),
                ),
                ("all_phases", models.BooleanField(default=False)),
                (
                    "duration_seconds",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "bilingual_mode",
                    models.CharField(
                        choices=[
                            ("alternate", "Hungarian pass, then English pass"),
                            ("stacked", "Both languages on one pass"),
                        ],
                        default="alternate",
                        max_length=9,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("order", models.SmallIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("kicker_hu", models.CharField(blank=True, max_length=80)),
                ("kicker_en", models.CharField(blank=True, max_length=80)),
                ("title_hu", models.CharField(max_length=120)),
                ("title_en", models.CharField(blank=True, max_length=120)),
                ("body_hu", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                ("footer_hu", models.CharField(blank=True, max_length=200)),
                ("footer_en", models.CharField(blank=True, max_length=200)),
                ("empty_hu", models.CharField(blank=True, max_length=200)),
                ("empty_en", models.CharField(blank=True, max_length=200)),
                ("column1_title_hu", models.CharField(blank=True, max_length=80)),
                ("column1_title_en", models.CharField(blank=True, max_length=80)),
                ("column2_title_hu", models.CharField(blank=True, max_length=80)),
                ("column2_title_en", models.CharField(blank=True, max_length=80)),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Section or column labels, bilingual, by key.",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="URL for the QR code. `wifi` encodes the Wi-Fi.",
                        max_length=500,
                    ),
                ),
                ("link_label_hu", models.CharField(blank=True, max_length=120)),
                ("link_label_en", models.CharField(blank=True, max_length=120)),
                ("link_qr", models.BooleanField(default=False)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Author notes. Never shown."),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("seed", "Seeded from YAML"),
                            ("admin", "Edited in the admin"),
                        ],
                        default="seed",
                        max_length=5,
                    ),
                ),
                (
                    "phases",
                    models.ManyToManyField(blank=True, related_name="slides", to="signage.phase"),
                ),
            ],
            options={
                "ordering": ("-priority", "order", "key"),
            },
            bases=(models.Model, signage.models.Bilingual),
        ),
        migrations.CreateModel(
            name="ScreenSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="signage.screen"
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="signage.slide"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("screen", "slide")},
            },
        ),
        migrations.AddField(
            model_name="screen",
            name="slides",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to show every slide of the current phase.",
                related_name="screens",
                through="signage.ScreenSlide",
                to="signage.slide",
            ),
        ),
        migrations.CreateModel(
            name="SlideItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                ("order", models.SmallIntegerField(default=0)),
                ("text_hu", models.CharField(max_length=240)),
                ("text_en", models.CharField(max_length=240)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Lucide icon name.", max_length=40),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="signage.slide",
                    ),
                ),
            ],
            options={
                "ordering": ("column", "order", "id"),
            },
        ),
    ]
